### ISSUE TITLE
Improve UX: The loader runs for just too long after send button is pressed

### ISSUE THREAD

**Issue by KShivendu** [shwosner/realtime-chat-supabase-react#1]
Hi @shwosner, thanks for creating this repository :) 
It appears to me that the current code hides the "messaging sending loader" only after the message has been delivered. But mostly, it takes a significant amount of time to get the response back. This heavily affects UX. Many people on the chat were complaining about that. I suggest you show the message instantaneously and make the message reddish or something if it fails. 

Cheers!

**Comment by shwosner** [comment]
@KShivendu correct, thanks for pointing that out.
I will change it to an 'optimistic response' when I have some extra time.

**Comment by shwosner** [comment]
@KShivendu I fixed the performance issue!
The UX feels much better now.

Some more updates
- Using now React Context
- Old messages will only load if the user scrolls up
- Button to 'scroll to the bottom'
- Badge with the number of new messages (if the scroll is not on the bottom)
- Added the sender's country flag

Thank you for your input, much appreciated :-)
