### ISSUE TITLE
Question about slicedMessages & Message in App context

### ISSUE THREAD

**Issue by tthias** [shwosner/realtime-chat-supabase-react#2]
Hi,

I'm using your repo to create my own chat with supabase, your code is amazing !
I was just wandering why you have both messages and slicedMessages in your app context ?

If I understand well they both have the exact same data, the only difference is that slicedMessages are in the reverse order. You are only using slicedMessages on your chat component, so why not just getting ride off messages and only use slicedMessages ?

Thanks a lot !

**Comment by tthias** [comment]
I got it, you set only the 10 last messages on the slicedMessages on the getInitialMessages to have a faster loading on the front end.

**Comment by shwosner** [comment]
Exactly, I see you figured it out 👍

You are welcome and thank you for using this repo.
