### ISSUE TITLE
relation "public.messages" does not exist "try to reconnect"

### ISSUE THREAD

**Issue by AsherCarneiro** [shwosner/realtime-chat-supabase-react#3]
Was just trying your repo with supabase to learn how things work and I added my API key and my project URL yet my app throws the error mentioned in the title after I "npm start". 

What do I need to configure on the supabase side to get things working?

Cause nothing is mentioned in <b> readme.md </b>

# ✌

**Comment by shwosner** [comment]
Please create a **messages** table in your database and try again.

Let me know if this helped.

**Comment by AsherCarneiro** [comment]
Hey! um i have build messages table on my database yet it isn't working do you have any screenshots as demo which I could follow.👏

**Comment by AsherCarneiro** [comment]
Hey so I have build messages.id, username and country column still I get the error "column messages.id does not exist
"

**Comment by shwosner** [comment]
@AsherCarneiro,

@winnekes took the time to update the documentation,
Have a look and let me know if it helps.

**Comment by AsherCarneiro** [comment]
> @AsherCarneiro,
> 
> @winnekes took the time to update the documentation,
> Have a look and let me know if it helps.

Hey I will try and let you know also thanks for your effort👏

**Comment by AsherCarneiro** [comment]
Hey, That helped a lot and the app worked!
