### ISSUE TITLE
Issues W/ useEffect

### ISSUE THREAD

**Issue by talmax1124** [shwosner/realtime-chat-supabase-react#6]
Hello! Awesome Repo! I filled the other missing useEffect Dependencies, but when doing the getMessagesAndSubscribe Dependency, It Says:

Compiled with warnings.

src/context/appContext.js
  Line 18:19:  'setIsGuest' is assigned a value but never used                                                                                                                                                                   no-unused-vars
  Line 73:16:  'getMessagesAndSubscribe' was used before it was defined                                                                                                                                                          no-use-before-define
  Line 108:9:  The 'getMessagesAndSubscribe' function makes the dependencies of useEffect Hook (at line 73) change on every render. To fix this, wrap the definition of 'getMessagesAndSubscribe' in its own useCallback() Hook  react-hooks/exhaustive-deps

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

but when i remove that dependency it says:

Compiled with warnings.

src/context/appContext.js
  Line 18:19:  'setIsGuest' is assigned a value but never used                                                                             no-unused-vars
  Line 73:6:   React Hook useEffect has a missing dependency: 'getMessagesAndSubscribe'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

Any Help? @shwosner @winnekes @AsherCarneiro

**Comment by arpitjacob** [comment]
Have these same errors when running the code

**Comment by shwosner** [comment]
@talmax1124 @arpitjacob
Are these warnings stopping your code from running?

**Comment by talmax1124** [comment]
Yes! @shwosner

**Comment by shwosner** [comment]
@talmax1124 
Seems to be strict es-lint rules that are blocking you, no?
Is it possible to share a codesandbox link?

**Comment by talmax1124** [comment]
@shwosner Could we hop on a discord call and work on it together from scratch to see if I'm doing something wrong?

**Comment by shwosner** [comment]
> @shwosner Could we hop on a discord call and work on it together from scratch to see if I'm doing something wrong?

Not at the moment, I'll contact you later by email.

**Comment by talmax1124** [comment]
Ok, what time zone are you in? So we could co-ordinate a time @shwosner

**Comment by shwosner** [comment]
> Ok, what time zone are you in? So we could co-ordinate a time @shwosner
New York

**Comment by talmax1124** [comment]
ok, I'm Est. Florida. So we have the same time. 5pm today works? @shwosner

**Comment by shwosner** [comment]
> ok, I'm Est. Florida. So we have the same time. 5pm today works? @shwosner

Yes, please email me at shwosner@gmail.com to continue the conversation.

**Comment by shwosner** [comment]
In case anyone else runs into this same issue.

Try adding this to the first line in `src/context/appContext.jsx`
```
/* eslint-disable react-hooks/exhaustive-deps */
```
