### ISSUE TITLE
user issues

### ISSUE THREAD

**Issue by japrozs** [shwosner/realtime-chat-supabase-react#7]
if u go to the website and change your name to someone who has sent a message in the chat, you'll be able to send messages as him.

**Comment by AsherCarneiro** [comment]
+1 I tested with diffrent users and it works i can send messages from their behalf

**Comment by japrozs** [comment]
> +1 I tested with diffrent users and it works i can send messages from their behalf lol how?
exactly!

**Comment by shwosner** [comment]
Hi @japrozs, @AsherCarneiro 

I've added today the option to log in with GitHub. 🥳
Messages from real usernames are getting a 'verified' badge.

I hope this helps 😊
