### ISSUE TITLE
Convert this to vite 

### ISSUE THREAD

**Issue by thatcatdrout** [shwosner/realtime-chat-supabase-react#8]
The development server is very slow so convert this to Vite. Or atleast make a realtime chat with vite

**Comment by shwosner** [comment]
Hi @thatcatdrout
Thanks for your feedback;

I converted the app to Vite 🎉
Also, I change the initial load should only fetch the last 50 messages, so the chat is now loading much faster.
(when you scroll to the top it loads more messages.)

I hope this helps :-)
